Project review
Marcraphael12/Review-For-Project-From-Trial pull request #1
Opened 2021-06-02 10:36 UTC by Marcraphael12

Discuss and review all updates in this project with others§
Thanks for leaving a comment, your review is welcome :- )

2021-06-02 13:58 UTC, Marcraphael12 commented
I think it would be better to:
- use the section tags instead of the main tags
- give your page a header
- make only one  radio button clickable

2021-06-02 14:01 UTC, Marcraphael12 commented
- There is nothing to says about your linters. Good job guy!
- I love the way your code is documented. Go ahead!

2021-06-02 14:04 UTC, Marcraphael12 commented
For me, you can now merge it, but pay attention to other comments to be sure that you are done!

2021-06-02 21:28 UTC, bolah2009 requested changes
Hi @Marcraphael12 ,

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!


## Required Changes ♻️


1. Let's use the GitHub inline comment. See the example inline comment review below.
2. I think your comments are not clear enough. Giving clear feedback helps with effective communication, instead of asking to make a change only also add "why" the changes are necessary. See this article on [How to give a code review](https://github.com/microverseinc/curriculum-transversal-skills/blob/main/code-review/articles/give_code_review_basics.md) for more details

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

- A nice tip to consolidate your reviews under a single summary is to click the "Start a review" button when adding the first review comment. This helps to house all your inline comment under one single summary like this current review. 😉 


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have only 3 code reviews per project. If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2021-06-02 21:28 UTC, bolah2009 commented on README.md
> +- LinkedIn: [](https://linkedin.com/in/linkedinhandle)
This is an example inline comment. 🙂 

You can see how it's under the main summary above and point to a specific part of the code where you want to suggest changes or just comment on it generally. 😉 

To do this, make sure you go to the "File changes" tab and use the "Start a review" button for your first review comment.

2021-06-02 23:27 UTC, Marcraphael12 commented on README.md
> +- LinkedIn: [](https://linkedin.com/in/linkedinhandle)
thanks a lot, I'm going to do it now!

2021-06-02 23:47 UTC, Marcraphael12 commented on index.html
> +            <input type="radio" id="id-psg-radio" value="PSG Team">
```suggestion
            <input type="radio" id="id-psg-radio" value="PSG Team">
            <input type="radio" id="id-barcelona-radio" name="Team" value="Barcelona">
            <input type="radio" id="id-real-madrid-radio" name="Team" value="Real Madrid">
```
I think it would be better if you:
-make only one radio button clickable.
   + when you select one item the first one stays checked. To fix that, you can make all of them unchecked by default!

2021-06-03 02:01 UTC, Spayco requested changes
Hi @Marcraphael12, 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.


 ## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have only 3 code reviews per project. If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2021-06-03 02:01 UTC, Spayco commented on index.html
> +            <input type="radio" id="id-psg-radio" value="PSG Team">
you've done well using Inline comments, but you should add at least 2, also please re-add the summary with it too so the review looks complete

2021-06-03 08:30 UTC, Marcraphael12 commented on index.html
> +            <input type="radio" id="id-psg-radio" value="PSG Team">
well, thank you!

2021-06-03 09:24 UTC, Marcraphael12 reviewed
You're on the right way! Just always takes care of your linters to be done with all content.

2021-06-03 09:24 UTC, Marcraphael12 commented on index.html
> +          <p><input type="submit" id="submit" value="submit"></p>
```suggestion
          <p><textarea placeholder="additional informations that we have to know about you" cols="30" rows="10"></textarea></p>
          <!--submit button-->
          <p><input type="submit" id="submit" value="Send your form"></p>
```
it would be better if you give your text area a default size. Define the number of characters the user may use to complete information!
Also, give an explicit value to the submit button. Maybe something like "send your form"

2021-06-03 11:42 UTC, nidalaa approved these changes
Hi @Marcraphael12 ,

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

You added a summary and an inline comment that is polite and explains why the change is requested. As in total you left more than 2 comments this project is approved :)



Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.


------
_As described in the [Students Handbook](https://www.notion.so/microverse/Project-reviews-022203ea6dd944b296b005533a19dcbe#cb67391d09f54bd98d6fed6ba24a4074) you have only 3 code reviews per project. If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2021-06-03 12:19 UTC, merged